name: superdeck_cli
description: Command line interface for SuperDeck
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck

executables:
  superdeck: main
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  yaml: ^3.1.3
  args: ^2.6.0
  path: ^1.9.0
  collection: ^1.18.0
  dart_style: ^3.0.1
  yaml_writer: ^2.0.1
  superdeck_core: ^0.0.1
  superdeck_builder: ^0.0.1
  mason_logger: ^0.3.1
  logging: ^1.3.0
  ack: ^0.1.1

dev_dependencies:
  dart_code_metrics_presets: ^2.19.0
  lints: ^5.0.0
  test: ^1.25.8
