name: superdeck
description: Presentation slides for Flutter with Flutter
version: 0.0.4
homepage: https://github.com/leoafarias/superdeck

publish_to: none

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"


dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  window_manager: ^0.4.3
  collection: ^1.18.0
  path: ^1.9.0
  syntax_highlight: ^0.4.0
  scrollable_positioned_list: ^0.3.8
  pdf: ^3.11.1
  shared_preferences: ^2.3.3
  go_router: ^14.2.7
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  mix: ^2.0.0-dev.4
  remix: ^0.1.0-beta.1
  flutter_markdown_plus: ^1.0.5
  superdeck_core: ^0.0.1
  markdown: ^7.3.0
  web: ^1.1.0
  file_saver: ^0.2.14
  image_picker: ^1.1.2
  open_filex: ^4.6.0
  auto_size_text: ^3.0.0
  material_symbols_icons: ^4.2780.0
  uri: ^1.0.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3
  google_fonts: ^6.3.2
  meta: ^1.16.0
  qr_flutter: ^4.1.0
  universal_html: ^2.2.4
  signals: ^6.2.0
  ack_annotations: ^1.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.7.5
  dart_code_metrics_presets: ^2.19.0
  integration_test:
    sdk: flutter
  build_runner: ^2.5.4
  ack_generator: ^1.0.0-beta.2

flutter:
  assets:
    - assets/
    - assets/grammars/
