name: superdeck_core
description: A core library for SuperDeck.
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck


environment:
  sdk: ">=3.9.0 <4.0.0"


# Add regular dependencies here.
dependencies:
  yaml: ^3.1.2
  collection: ^1.18.0
  path: ^1.9.0
  meta: ^1.15.0
  ack: ^1.0.0-beta.2
  markdown: ^7.3.0
  logging: ^1.3.0
  uuid: ^4.0.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  dart_code_metrics_presets: ^2.19.0
