name: superdeck_builder
description: The build logic for SuperDeck presentations
version: 0.0.1
homepage: https://github.com/leoafarias/superdeck

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  superdeck_core: ^0.0.1
  logging: ^1.3.0
  path: ^1.9.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.1
  collection: ^1.18.0
  puppeteer: ^3.17.0
  crypto: ^3.0.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
  dart_code_metrics_presets: ^2.19.0 